name: Build & Release

on:
  workflow_dispatch:

jobs:
  build_and_package:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}

    steps:
      - name: Download code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Run integration tests
        run: ./gradlew integrationTest
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          LICENSE_KEY: ${{ secrets.LICENSE_KEY }}


  make_release:
    runs-on: ubuntu-latest
    needs: build_and_package
    permissions: write-all

    env:
      GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}

    steps:
      - name: Download code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Conventional changelog action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.PACKAGE_TOKEN }}
          skip-on-empty: "true"
          skip-commit: "true"
          tag-prefix: ''
          output-file: false
          skip-version-file: "true"
          skip-git-pull: "true"
          fallback-version: "0.1.0"
          skip-tag: "true"

      - name: Fetch new version
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          NEW_VERSION=${{ steps.changelog.outputs.version }}
          echo "Creating new version: $NEW_VERSION"
          echo NEW_VERSION=$NEW_VERSION >> $GITHUB_ENV

      - name: Create release zip
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: ./gradlew createRelease -Pversion=${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Create release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: ${{ env.NEW_VERSION }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          files: ./build/distributions/plugin-artifacts.zip
